// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectNode(arg1:string):Promise<void>;

export function GetAppState():Promise<main.AppState>;

export function GetFrontendState():Promise<main.FrontendState>;

export function Greet(arg1:string):Promise<string>;

export function LogPrintln(arg1:string):Promise<number>;

export function MarkFrontendReady():Promise<void>;

export function NewDataNotify():Promise<void>;

export function StartGlobalStats():Promise<void>;

export function StartRecording():Promise<void>;

export function StartSim(arg1:number):Promise<void>;

export function StopGlobalStats():Promise<void>;

export function StopRecording():Promise<void>;

export function StopSim():Promise<void>;
