// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectNode(arg1) {
  return window['go']['main']['App']['ConnectNode'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetFrontendState() {
  return window['go']['main']['App']['GetFrontendState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogPrintln(arg1) {
  return window['go']['main']['App']['LogPrintln'](arg1);
}

export function MarkFrontendReady() {
  return window['go']['main']['App']['MarkFrontendReady']();
}

export function NewDataNotify() {
  return window['go']['main']['App']['NewDataNotify']();
}

export function StartGlobalStats() {
  return window['go']['main']['App']['StartGlobalStats']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StartSim(arg1) {
  return window['go']['main']['App']['StartSim'](arg1);
}

export function StopGlobalStats() {
  return window['go']['main']['App']['StopGlobalStats']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function StopSim() {
  return window['go']['main']['App']['StopSim']();
}
